"""
Read in .gcoords output and insert two columns of 0.0 values for Ks and Kn

Input: .gcoords output generated by GeneOrder.py

Output: .gcoords output with two columns of 0.0 values for Ks and Kn
"""
from os import path

def kscalc_zero(context, *args, **kwargs):
    
    output = path.join(context.createoutdir(), path.basename(args[0]) + ".ks")

    # Read in the input file and write the output file with two 0.0 values for Ks and Kn
    with open(args[0], 'r') as infile, open(output, 'w') as outfile:
        # skip first line
        infile.readline()
        
        # write header lines
        outfile.write("#This file contains synonymous rate values in the first two columns:\n")

        for line in infile:
            if line.startswith("#"):
                outfile.write(line.strip() + "  Mean Ks:  0.0\tMean Kn: 0.0\n")
                outfile.write("#Ks\tKn\ta<db_genome_id>_<chr>\tchr1||start1||stop1||name1||strand1||type1||db_feature_id1||genome_order1||percent_id1\tstart1\tstop1\tb<db_genome_id>_<chr>\tchr2||start2||stop2||name2||strand2||type2||db_feature_id2||genome_order2||percent_id2\tstart2\tstop2\teval\tblock_score\tGEVO_link\n")
            else:
                outfile.write('0.0\t0.0\t' + line)
    
    return output